version: '2'
services:
  express-docker:
    build:
        context: ./
        dockerfile: ./.docker/Dockerfile
    container_name: express-docker-node
    restart: always
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
    ports:
      - '8080:8080'
